function S = steps()
%STEPS  The calibration ladder: a CGM core built up to the production model.
%
%   S = ladder.steps()
%
%   Each step is one change to the calibration, applied on top of every step
%   before it. Step 1 replaces production values with a Cocco, Gomes and
%   Maenhout (2005) core inside this model's time structure, and each later
%   step restores one feature, so the last step reproduces config.params().
%
%   To change the calibration, edit a value in a step, or append a step at the
%   end -- for example a consumption-floor level, a housing multiple from data,
%   or the REIT leg. Fields:
%     name    identifier used in file names; unique
%     label   one line for titles
%     note    where the values come from, one line
%     set     parameter overrides; every field must be a primitive of
%             config.params (config.params(false) lists them)
%
%   Fixed throughout, as deviations from CGM: entry at 25 rather than 20, a
%   terminal age of 100, Dutch unisex mortality, and no transitory income
%   shock (log income is a random walk with CGM's permanent variance).

S = struct('name', {}, 'label', {}, 'note', {}, 'set', {});

S(end+1) = step('cgm', 'CGM (2005) core', ...
    ['gamma 10, high-school income cubic, 68.2% replacement at 65, r 2%, ' ...
     'equity premium 4%, vol 15.7%; no housing, pension or taxes'], ...
    struct('gamma', 10, 'retirement_age', 65, 'income_source', 'poly', ...
           'replacement', 0.68212, 'r', 0.02, 'mu_S_level', 0.04, ...
           'sigma_S_level', 0.157, 'h_mult', 0, 'kappa_base', 0, 'tau_inc', 0, ...
           'tau_cg_bond', 0, 'tau_cg_stock', 0, 'tau_wealth', 0, 'tau_REIT', 0));

S(end+1) = step('gamma5', 'Risk aversion 5', ...
    'Production value', ...
    struct('gamma', 5));

S(end+1) = step('retire67', 'Retirement at 67', ...
    'Statutory AOW age', ...
    struct('retirement_age', 67));

S(end+1) = step('income', 'Dutch income profile', ...
    'Been, Knoef & Vethaak (2026) age effects, men, 2025 euros', ...
    struct('income_source', 'table'));

S(end+1) = step('market', 'Dutch financial market', ...
    'Real T-bill rate 1.1%, equity volatility 16%', ...
    struct('r', 0.011, 'sigma_S_level', 0.16));

S(end+1) = step('housing', 'Housing', ...
    ['H at 4x entry income: renters pay 6% rent on a rent index growing ' ...
     '0.97% real; owners pay 1.5% maintenance and a 30-year annuity mortgage'], ...
    struct('h_mult', 4));

S(end+1) = step('pension', 'AOW and DC pension', ...
    ['AOW replaces 30.7% of final wage; DC contributions of 18.6% above ' ...
     'the franchise, glide-path fund, annuitised at 67'], ...
    struct('replacement', 0.307, 'kappa_base', 0.186));

S(end+1) = step('inctax', 'Income tax', ...
    'EET at 38.2% on wages, AOW and annuity payouts', ...
    struct('tau_inc', 0.382));

S(end+1) = step('box3', 'Box-3 tax', ...
    '36% on the liquid account''s returns, no loss offset', ...
    struct('tau_cg_bond', 0.36, 'tau_cg_stock', 0.36));
end

function s = step(name, label, note, set)
s = struct('name', name, 'label', label, 'note', note, 'set', set);
end
